Feature/check translates
Innim/alex pull request #34
Opened 2022-11-29 13:15 UTC by ulezkin

2022-12-01 06:55 UTC, greymag requested changes

2022-12-01 06:55 UTC, greymag commented on README.md
> +#### Check translations for all locale strings (en by default)
Не очень понял - написано "for all locale strings", но в примере команды явное указание одной локали.

2022-12-01 06:55 UTC, greymag commented on README.md
>  Also you can export json localization to xml.
Это же относится к to_xml

2022-12-01 06:55 UTC, greymag commented on lib/commands/release/start_release_command.dart
> +            'If not specified - all locales will be imported.',
Описание неподходящее

2022-12-01 06:55 UTC, greymag commented on lib/commands/release/start_release_command.dart
> +    static const _argLocale = 'locale';
Проблема с форматированием, и название аргумента плохое - в контексте релиза не понятно что это за локаль

2022-12-01 06:55 UTC, greymag commented on lib/commands/release/start_release_command.dart
> +    final checkTranslateResult = await comparer.compare(
Не понятно что конкретно записывается в эту переменную

2022-12-01 06:55 UTC, greymag commented on lib/commands/release/start_release_command.dart
> +  final config = findConfigAndSetWorkingDir();
Все что ниже - вынеси в отдельный метод

2022-12-01 06:55 UTC, greymag commented on lib/commands/release/start_release_command.dart
> +        await runIntlOrFail(
Это (генерацию arb) тоже надо выносить в отдельный утилитарный метод, раз используется в разных местах

2022-12-01 06:55 UTC, greymag commented on lib/runner/alex_command.dart
> +import '../src/pub_spec.dart';
Абсолютный импорт

2022-12-01 06:55 UTC, greymag commented on lib/commands/l10n/check_translate_command.dart
> +/// Command to extract strings from Dart code to arb file.
Дока

2022-12-01 06:55 UTC, greymag commented on lib/commands/l10n/check_translate_command.dart
> +            'Checks for translations for a language, the default is English.') {
Не очень понятно что подразумевается под "проверкой переводов". Уточни что проверяется просто наличие переводов на определенный язык) А то проверка может быть разная

2022-12-01 06:55 UTC, greymag commented on lib/commands/l10n/check_translate_command.dart
> +            'If not specified - all locales will be imported.',
Копипаста

2022-12-01 06:55 UTC, greymag commented on lib/src/l10n/comparers/arb_comparer.dart
> +import '../../exception/run_exception.dart';
импорт

2022-12-01 06:55 UTC, greymag commented on lib/src/l10n/comparers/arb_comparer.dart
> +  Future<int> compare(
Ты внес уровень команды (ошибка/успех) на уровень утилитарного класса - не надо так делать. Утилитарный класс должен быть написан таким образом, чтобы он делал свою работу и возвращал результат, вне зависимости от того, кто его вызвал. А уже если вызвала команда - то пусть она и выводит ошибку, успех и тп.

В случае ошибок в алекс принято кидать исключение, где ты всю необходимую информацию можешь предоставить.

2022-12-01 06:55 UTC, greymag commented on lib/src/l10n/comparers/arb_comparer.dart
> +            message: 'All strings has translete for locale: $locale');
Опечатка

2022-12-01 12:29 UTC, ulezkin commented on lib/commands/release/start_release_command.dart
> +        await runIntlOrFail(
Вынес в миксин.

2022-12-02 06:34 UTC, greymag requested changes

2022-12-02 06:34 UTC, greymag commented on lib/commands/release/start_release_command.dart
> +        help: 'Locale to check availability translations before release. '
```suggestion
        help: 'Locale to check before release if translations exist for all strings. '
```

2022-12-02 06:34 UTC, greymag commented on lib/commands/release/start_release_command.dart
> +    return success();
Тут не очень хорошо вызывать `success()`, т.к. по логике он должен вызываться только один раз, когда команда завершена

2022-12-02 06:34 UTC, greymag commented on lib/commands/release/start_release_command.dart
> +  Future<int> _checkTranslatations(ArgResults args) async {
Лучше принимать не целиком объект аргументов, а уже конкретное значение, разбор аргументов, как правило, мы оставляем в основном методе.

2022-12-02 06:34 UTC, greymag commented on lib/commands/release/start_release_command.dart
> +          await runIntlOrFail(
Все еще используется команда напрямую, должен быть просто метод, типа "извлечь локализацию"

2022-12-02 06:34 UTC, greymag commented on lib/commands/release/start_release_command.dart
> +class StartReleaseCommand extends AlexCommand  with IntlMixim{
```suggestion
class StartReleaseCommand extends AlexCommand  with IntlMixim {
```

2022-12-02 06:34 UTC, greymag commented on lib/commands/l10n/check_translate_command.dart
> +class CheckTranslateCommand extends L10nCommandBase with IntlMixim {
`IntlMixim` - это часть локализации, по идее должен быть подключен в базовый класс `L10nCommandBase`, а не отдельно в каждом классе команды локализации

2022-12-02 06:34 UTC, greymag commented on lib/commands/l10n/check_translate_command.dart
> +            'Checks availability translations into a specific language, the default is English.') {
"availability" - "доступность", здесь не очень подходящий термин. Пиши явно, что проверяешь есть переводы всех строк или нет (exist)

2022-12-02 06:34 UTC, greymag commented on lib/commands/l10n/check_translate_command.dart
> +        help: 'Locale for check availability translations. '
Написал пример в start_release команде

2022-12-02 13:16 UTC, merged